language: node_js
sudo: false
node_js:
- '0.12'
- '0.11'
- '0.10'
before_install:
- cp ci/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- cp ci/npm-config.sh $HOME/
- chmod +x $HOME/npm-config.sh
- "$HOME/travis-ci.sh before-install"
before_script:
- "$HOME/travis-ci.sh before-script"
script:
- "$HOME/travis-ci.sh script"
after_script:
- "$HOME/travis-ci.sh after-script"
after_success:
- "$HOME/travis-ci.sh after-success"
before_deploy:
- "$HOME/travis-ci.sh before-deploy"
- cd built
after_deploy:
- "$HOME/travis-ci.sh after-deploy"
cache:
  directories:
  - node_modules
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalamuna.com
    - ben@kalamuna.com
    on_success: always
env:
  global:
  - secure: T3NJyfDCjlh0b4PcGOvML4BsDno7mT7xutIrJ7h0oMPnMQ7aktPEVutsHaTtyjReHI9XhYxIpIq0sblAtrym/TY0xRC9wb2i3E24dbF/AXvXYhUwIun2cQhBt+GH9SR7FNDdz4FcoXjMUJj2G17JIWDu+S4oDZAm0iwiSG7CAwPk22w42Dd0ucK8icB/QobwoL8ya/i+AKyiNMmAh2j3857+nxjG/1QuYEUeXaHqZAdz4hsuGklMEUheAk1j4UVxodechmMhRWdtQhN5fVYjvvQfNJYYWMyFjcRxpV0p5Hw+mRK6SA1BuWxIU/E0rhPBo6iYnH6AWb363dRtltqdEHtuHKvm95rBZLbBRYJOGekHGOAfQ1iMUW67wdSmI1/H5bWxuiRKK4Zt2HQrkzQqeAQiSXvOr2KkxLSCDzbHxPKRLEac7g8PQy2Nl4IK3HyVkt2dPk9KLqt3WSvg35itrWNmT1O6gunyQHptdxQKvIgeYfaO1xJgy+YLGNzjHFam2LpDTW9729R9JU53k7R9ECw6A9b/aRt5+6YqK0OKhMhKDEIGXc7AXSHbUrE1zT4eLIVYkFPN2HvCuTMMXSlaxSuosP2w+2WJB26HxfemJkeVibngmr5A2/zKniVj7CEfbvMIu5plcocxFPikKycRhDfToYI6pqLS2DF/8gGsMwg=
  - secure: nVWlWjdW2HIzX8nRBeiLiFf1qk6/DJETSzp2oS6nsaanKxi4bHCloG6no6JzIZzfRVPobSa08EsTyoEspJClzjsG+jiplDifjfYwPhuF9dw+6X9fjZPLaThp8dzLOwo+LS6YTaDNHjUszh1WvCKRE95SXT/1zdhpLLZuIjMUPuWFi8krN7JUHBHVUVYEYAKzYTzqyzzdOYEcpikoIlAggRa4hNUaiJOfqok7yv3GeI7TubIik28jpASt4uiB39sVWPwRPNNrFOfUcewae7gihXWqOP2eD8xS99L8e3guxxY7HhK65L/psKhNL/GhgctmT2s+HQvc7M7cnjIlb1f6QqXVbDeps9IQjhshHVEildElc+KqZOroPnVeSumFnGjK5HfEN7f1OMQk2+Nfi/Zfk5OWkqqngKdpbVhOdlaJVBckk++0r68dm3ba9ve8NhOTrGVryVwXR4KJVogB+kaKZuPfNIpM26oSLZrBRfEl6bzgwxuwwfB0Hax3EG6EtWREzQxHroFlLxsYAMLhyVJ2IruskGrGyP9Ww+8a/SV+QwzyOeik4VLhdw5vCHr/QXCfaOvoXrGKV012/rSs0eBhSZZDsPZ7vMdAwMg8XaEBegaGqrgiOlAza6VmwRkxj9jMw0DWkVLxc+kdUzNnNlKoYmv9PG5G4CULklEniAFd9U8=
  - secure: H9ZM5LbpfYv35/vK+kdlqBHnEdUAKHRqks/6YKb8C49KD9lcFFJcn+pzmxBrKX9yVuffDTibFAbbjLw7Fnu1tzr6hzJZu0JvQuEjybGhwXc3mcr3iRtVw0aoVydyw3D5aSlLR6Lxaned97cdmpoxqdgDi0RYzd5GjRgX6mGSg6Lhc4Uo3HiIeK4tGnaDn4gLToxPDqj+9g5tVymSYQjqwKanXPg404F/TaxfT/ezYLrK5HwQ0DuL/F9v1HCKx53m6p9c54FuQAtIQzu6MAsFMzReZy6tp54R0HaNCcS6JK3w0FBN3OWYW2GdzDuFWXxFy+w5+g7uyIXhE5YyZOyZ5B1D8GrPi8f+TflsQLX26ddYFbli1Q77bMQBU7SSZ4k6ya9ydH9gBqMi3rMl32wxADb7tQ8TB/UtuLgIno7YZSCN3BrKUMuhRv0/hOUBTRWNXLzuo8iO+QQVpA8bDDuID6QghLg0h1J/TW0jDxjGyzJM8aHcmfxHHSp+b0cCtLlYh9Pxe6hRaxfF+lFepIIzezfn5UwedS+gDMchEAsBaq5te4kyGO4tF0/fqeoiypE3dfXFuOTLLZFjN04UwfViB+B91IyHmcJ/t5oKwBKQ4OFILCK52Xehugm9lZFQQs605yz3HV5RxBziV4j1+tiHkpKMNSiNJkRbRphWrGzpVms=
